# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21f08558ea647548852cb5a7941b30387dfa56ea6efedccb35a7b43cca33c0768b4a08c838c2604e7b0e29534c998128449c4e9b34536dca00534364f11ff5bf

test:
  secret_key_base: fbff9305c1dc2edf5bd354e5cdd3e9f5556e8e2b4b1bdd7bbed50e04d3f764bc8c3496c1e83097109d89816ee5c0f51651b064df36882a95a91873d400898749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
